# Generated by Django 4.2.28 on 2026-03-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='problem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
