# Generated by Django 4.2.28 on 2026-03-08 05:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0003_problemattemmpt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemAttemmpt',
            new_name='ProblemAttempt',
        ),
    ]
