# Generated by Django 4.2.28 on 2026-05-25 14:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_rename_problemattemmpt_problemattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
