# Generated by Django 4.2.28 on 2026-08-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ace_mode',
            field=models.CharField(choices=[('python', 'Python'), ('c_cpp', 'C / C++'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('mysql', 'MySQL'), ('golang', 'Go'), ('ruby', 'Ruby'), ('text', 'Plain Text')], default='text', max_length=50),
        ),
    ]
