# Generated by Django 4.2.28 on 2026-09-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemattempt',
            name='correct_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problemattempt',
            name='next_review_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
