# Generated by Django 4.2.28 on 2026-09-13 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_alter_problem_options_alter_problem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ace_mode', models.CharField(choices=[('python', 'Python'), ('c_cpp', 'C / C++'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('mysql', 'MySQL'), ('golang', 'Go'), ('ruby', 'Ruby'), ('text', 'Plain Text')], default='text', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='problems.language'),
        ),
    ]
