# Generated by Django 4.2.28 on 2026-09-13 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_language_problem_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ace_mode',
        ),
        migrations.AlterField(
            model_name='problem',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='problems.language'),
        ),
    ]
