# Generated by Django 4.2.28 on 2026-09-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_remove_category_ace_mode_alter_problem_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['language', 'category', 'order']},
        ),
    ]
