# Generated by Django 4.2.28 on 2026-09-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_alter_problem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='order_matters',
            field=models.BooleanField(default=False, help_text='If True, row order in SQL results must match reference_query exactly'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('code', 'Code Recall'), ('sql', 'SQL Query')], default='code', max_length=10),
        ),
    ]
